id: IE8125A83
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:26:50+00:00'
last_modified: '2022-06-07T22:21:07.698894+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03746
  title: པདྨ་ཐང་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B1B6:
      image_group_id: I00KG03751
      title: ''
      total_pages: 562
      order: 1
      base_file: B1B6.txt
    6A2F:
      image_group_id: I00KG03752
      title: ''
      total_pages: 600
      order: 2
      base_file: 6A2F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
